name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #push:
  #  tags:
  #    - "[0-9]+.[0-9]+.[0-9]+"

env:
  configuration: Release

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Verify commit exists in origin/master
      #  run: |
      #    git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      #    git branch --remote --contains | grep origin/master

      #- name: Set VERSION variable from tag
      #  run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore -c ${{ env.configuration }} /p:Version=1.1.0 /p:ContinuousIntegrationBuild=true

      - name: Test
        run: dotnet test --no-build -c ${{ env.configuration }} /p:Version=1.1.0 --no-build

      - name: Pack
        run: dotnet pack --no-build -c ${{ env.configuration }} /p:Version=1.1.0 --output .

      - name: Push
        run: dotnet nuget push DynamicNotifyPropertyChanged.1.1.0.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
